"""NEC2 solver adapter — the second solver family (Phase 2 #6).

Why this exists: the project's claim is that the *neutral model* is solver-independent.
openEMS (FDTD, planar/dielectric) is one adapter; a wire antenna needs a method-of-moments
engine instead.  This adapter renders a NEC2 input deck from a :class:`WireDesign` and
parses the classic NEC output, so the same geometry description can be handed to a
different solver without touching the model layer.

Scope note (honest): this adapter takes a ``WireDesign`` directly.  Hooking a wire
section into :class:`~openantenna.model.project.Project` is a model-layer change that
belongs with the package owner; until then the wire path is "neutral geometry -> second
adapter", which is exactly the abstraction being demonstrated.

The binary is looked up in this order: ``NEC2_BIN`` environment variable, then
``nec2c`` / ``nec2++`` / ``nec2c.exe`` on ``PATH``.  Nothing is faked: if the engine is
missing, :meth:`Nec2Solver.available` says so and :meth:`Nec2Solver.run` raises instead
of inventing results.

Usage::

    solver = Nec2Solver()
    solver.prepare(design, "runs/dipole")
    run = solver.run("runs/dipole")
    parsed = solver.parse_results("runs/dipole")
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional

from ..geometry.wire import WireDesign
from .base import SolverAdapter, SolverRun, SolverStatus, SolverUnavailableError

DECK_NAME = "model.nec"
OUTPUT_NAME = "nec2.out"

#: a signed number, with or without an exponent (NEC2 prints E-notation)
_NUMBER = r"-?[0-9]+(?:\.[0-9]*)?(?:[Ee][+-]?[0-9]+)?"

#: NEC2's input-parameter row: tag, segment, then 9 numbers
#: (V re/im, I re/im, Z re/im, Y re/im, power).  The frequency is not in this row:
#: it comes from the "FREQUENCY : <f> MHz" line that precedes the block.
_FREQ_LINE = re.compile(r"FREQUENCY\s*:\s*([0-9.]+[Ee]?[+-]?[0-9]*)\s*MHz", re.I)
_INPUT_ROW = re.compile(
    r"^\s*(\d+)\s+(\d+)\s+" + r"\s+".join([f"({_NUMBER})"] * 9) + r"\s*$", re.M
)
_EFFICIENCY = re.compile(r"EFFICIENCY\s*=\s*([0-9.]+)\s*Percent", re.I)


class Nec2Solver(SolverAdapter):
    """Adapter for a NEC2-compatible engine (nec2c, nec2++)."""

    name = "nec2"

    def __init__(self, binary: Optional[str] = None) -> None:
        self._binary = binary

    # ------------------------------------------------------------------ probe
    def resolve_binary(self) -> Optional[str]:
        """Return a usable engine path, or None when nothing usable is configured."""
        if self._binary:
            return self._binary if Path(self._binary).exists() else None
        env = os.environ.get("NEC2_BIN")
        if env:
            return env if Path(env).exists() else None
        for candidate in ("nec2c", "nec2++", "nec2c.exe", "necpp"):
            found = shutil.which(candidate)
            if found:
                return found
        return None

    def available(self) -> SolverStatus:
        binary = self.resolve_binary()
        if binary is None:
            configured = self._binary or os.environ.get("NEC2_BIN")
            if configured:
                detail = (
                    f"the configured NEC2 engine does not exist: {configured}; "
                    "fix NEC2_BIN or pass an existing binary"
                )
            else:
                detail = (
                    "no NEC2 engine found; set NEC2_BIN (or put nec2c / nec2++ on PATH). "
                    f"Deck generation still works: prepare() always writes {DECK_NAME}."
                )
            return SolverStatus(name=self.name, available=False, detail=detail)
        return SolverStatus(
            name=self.name,
            available=True,
            detail=f"NEC2 engine found: {binary}",
            binary_path=str(binary),
        )

    # ----------------------------------------------------------------- render
    def render_deck(self, design: WireDesign, comment: str = "OpenAntenna Studio") -> str:
        """Render a NEC2 deck for ``design`` (GW / GE / EX / FR / EN cards)."""
        length = design.length_m
        radius = design.radius_m
        freq_mhz = design.frequency_hz / 1e6
        segments = design.segments
        feed_segment = (segments + 1) // 2  # odd segment count -> centre segment

        lines = [
            f"CM {comment} - wire antenna, generated by openantenna.solvers.nec2",
            "CE",
        ]
        if design.ground_plane:
            lines.append("GN 1")  # perfect ground
            lines.append(f"GW 1,{segments},0.,0.,0.,0.,0.,{length:.6f},{radius:.6f}")
        else:
            half = length / 2.0
            lines.append(
                f"GW 1,{segments},0.,0.,{-half:.6f},0.,0.,{half:.6f},{radius:.6f}"
            )
        # Free-format with commas, exactly like the decks shipped with nec2c: an
        # extra integer field precedes the voltage on the EX card (I3 is unused for
        # a voltage source, the voltage is I4 and the phase I5).  Without that field
        # nec2c reports 'NON-NUMERICAL CHARACTER . IN INTEGER FIELD'.
        lines += [
            "GE 0",
            f"EX 0,1,{feed_segment},0,1.0,0.0",
            f"FR 0,1,0,0,{freq_mhz:.6f},0.0",
            "RP 0,91,1,1000,0.,0.,2.,0.",  # principal-plane pattern request
            "EN",
        ]
        return "\n".join(lines) + "\n"

    def prepare(self, project, rundir) -> Path:  # type: ignore[override]
        if not isinstance(project, WireDesign):
            raise TypeError(
                "Nec2Solver.prepare expects a WireDesign (the wire path is not yet part of "
                "Project); got "
                f"{type(project).__name__}"
            )
        path = Path(rundir)
        path.mkdir(parents=True, exist_ok=True)
        (path / DECK_NAME).write_text(self.render_deck(project), encoding="utf-8")
        return path

    # -------------------------------------------------------------------- run
    def run(self, rundir, timeout_s: Optional[float] = None) -> SolverRun:  # type: ignore[override]
        status = self.available()
        if not status.available:
            raise SolverUnavailableError(status.detail)
        path = Path(rundir)
        deck = path / DECK_NAME
        if not deck.exists():
            raise FileNotFoundError(f"{deck} not found; call prepare() first")
        output = path / OUTPUT_NAME

        # nec2c takes -i/-o; nec2++ and friends read the deck on stdin.  nec2c also
        # refuses file names longer than ~80 characters, so the deck is addressed
        # RELATIVE to the run directory (cwd) and the report is left there too.
        completed = subprocess.run(
            [status.binary_path, f"-i{DECK_NAME}", f"-o{OUTPUT_NAME}"],
            cwd=str(path),
            capture_output=True,
            timeout=timeout_s,
            check=False,
        )
        text = (completed.stdout or b"").decode("utf-8", errors="replace")
        text += (completed.stderr or b"").decode("utf-8", errors="replace")
        produced = output.exists() and output.stat().st_size > 0
        returncode = completed.returncode
        if not produced:
            with deck.open("rb") as handle:
                piped = subprocess.run(
                    [status.binary_path],
                    input=handle.read(),
                    cwd=str(path),
                    capture_output=True,
                    timeout=timeout_s,
                    check=False,
                )
            piped_text = (piped.stdout or b"").decode("utf-8", errors="replace")
            piped_text += (piped.stderr or b"").decode("utf-8", errors="replace")
            if piped_text.strip():
                text = piped_text
                output.write_text(text, encoding="utf-8")
                produced = True
                returncode = piped.returncode
            elif not text.strip():
                output.write_text(text, encoding="utf-8")
        return SolverRun(
            rundir=path,
            status="ok" if returncode == 0 and produced else "failed",
            returncode=returncode,
            log=text,
            outputs={OUTPUT_NAME: str(output)} if produced else {},
        )

    # ------------------------------------------------------------------ parse
    def parse_results(self, rundir) -> Dict[str, Any]:  # type: ignore[override]
        path = Path(rundir)
        output = path / OUTPUT_NAME
        if not output.exists():
            raise FileNotFoundError(
                f"{output} not found; the engine has not produced a report yet"
            )
        text = output.read_text(encoding="utf-8", errors="replace")
        freqs = [float(m.group(1)) for m in _FREQ_LINE.finditer(text)]

        # one impedance row per frequency, taken only from the input-parameter blocks
        rows: list[tuple[float, float, float, float, float]] = []
        for block_index, header in enumerate(re.finditer(r"ANTENNA INPUT PARAMETERS", text)):
            region = text[header.end():]
            for stop in ("CURRENTS AND LOCATION", "ANTENNA INPUT PARAMETERS"):
                position = region.find(stop)
                if position > 0:
                    region = region[:position]
            match = _INPUT_ROW.search(region)
            if match is None:
                continue
            values = [float(v) for v in match.groups()[2:]]
            # tag, segment, then V_re V_im I_re I_im Z_re Z_im Y_re Y_im P
            z_re, z_im = values[4], values[5]
            frequency_hz = freqs[block_index] * 1e6 if block_index < len(freqs) else float("nan")
            rows.append((frequency_hz, z_re, z_im, values[8], 0.0))

        if not rows:
            raise ValueError(
                f"no antenna input-parameter row found in {output.name}; the deck may have "
                "failed to run (check the raw output)"
            )
        frequency_hz, resistance, reactance, _, _ = rows[0]
        impedance = complex(resistance, reactance)
        efficiency = _EFFICIENCY.search(text)
        result: Dict[str, Any] = {
            "solver": self.name,
            "frequency_hz": frequency_hz,
            "resistance_ohm": resistance,
            "reactance_ohm": reactance,
            "impedance_ohm": [resistance, reactance],
            "vswr_50_ohm": self._vswr(impedance, 50.0),
            "n_frequencies": len(rows),
            "blocks": [
                {"frequency_hz": f, "resistance_ohm": r, "reactance_ohm": x} for f, r, x, _, _ in rows
            ],
            "note": (
                "wire antennas are reported as input impedance, not S11: NEC2's classic "
                "output has no reference impedance, so the VSWR column is derived for 50 ohm"
            ),
        }
        if efficiency:
            result["efficiency_percent"] = float(efficiency.group(1))
        return result

    @staticmethod
    def _vswr(z: complex, z0: float) -> float:
        """VSWR of ``z`` against ``z0``; infinite for a short (z = -z0) or worse."""
        if abs(z + z0) < 1e-12:
            return float("inf")
        gamma = abs((z - z0) / (z + z0))
        return float("inf") if gamma >= 1.0 else (1.0 + gamma) / (1.0 - gamma)
