"""openEMS / CSXCAD adapter.

PHASE 1 SCOPE - READ THIS FIRST
-------------------------------
This module **generates** a runnable openEMS model script from the neutral
project model.  It does not, and cannot, execute it here:

* no openEMS/CSXCAD runtime was installed in the environment where this module
  was written, so :meth:`OpenEMSSolver.available` returns ``False`` there;
* the generated script has therefore only been **statically reviewed** against
  the documented CSXCAD/openEMS Python API.  It is explicitly *not* a verified
  simulation.  Expect to correct API details on the first real run and record
  what changed.

Licensing: openEMS is GPL-3.0-or-later and CSXCAD is LGPL-3.0-or-later.  Both are
driven here as **external programs** via generated scripts and files, never as
imported libraries, so this MIT-licensed package stays a separate work.  See
``docs/licensing.md``.

Geometry conventions used by the generated script (metres, right-handed):

* z = 0 is the top of the substrate (the patch plane);
* the substrate occupies ``z in [-h_total, 0]``;
* the ground plane sits just below the substrate;
* patch width ``W`` along x, patch length ``L`` along y;
* the feed (lumped port) runs along z from the ground plane up to the patch;
  its (x, y) position depends on ``feed_mode``:
    - ``edge``  -> y = +L/2 (radiating edge)
    - ``inset`` -> y = +L/2 - inset_depth
    - ``probe`` -> (0, 0), i.e. the patch centre
"""

from __future__ import annotations

import json
import math
import os
import shutil
import sys
from importlib import util as importlib_util
from pathlib import Path
from string import Template
from typing import Any, Callable, Dict, Optional

from ..geometry.array import build_array_layout
from ..geometry.patch import ground_plane_size, synthesize_patch
from ..materials.library import get_material
from ..model.project import C0, Project
from .base import SolverAdapter, SolverRun, SolverStatus, SolverUnavailableError

GENERATOR_VERSION = "0.1.0"
EPS0 = 8.8541878128e-12  # vacuum permittivity [F/m]

_SCRIPT_TEMPLATE = Template(
    '''#!/usr/bin/env python
"""openEMS model generated by OpenAntenna Studio $VERSION.

Source project : $PROJECT_NAME
Generated by   : openantenna.solvers.openems.OpenEMSSolver.render_script()

*** THIS SCRIPT HAS NEVER BEEN EXECUTED ***
It was generated in an environment without an openEMS/CSXCAD runtime, so it has
only been reviewed statically against the documented Python API.  Expect to fix
details on the first real run, and write down what you changed.

Licensing: this script drives openEMS (GPL-3.0-or-later) and CSXCAD
(LGPL-3.0-or-later) as an external program.  It is not linked into, and is not
part of, OpenAntenna Studio (MIT).

Units: metres (SetDeltaUnit(1.0)), Hz.
Coordinate conventions: z = 0 is the top of the substrate; patch width W along
x, patch length L along y; the lumped port runs along z through the substrate.
"""

import csv
import json
import os
import sys

# --- Windows: the openEMS package ships its native DLLs (CSXCAD.dll,
# --- openEMS.dll, hdf5, vtk, ...) next to its executables.  Since Python 3.8
# --- extension modules no longer search PATH for dependent DLLs, so the
# --- directory must be registered explicitly before importing CSXCAD.
if os.name == "nt":
    _root = os.environ.get("OPENEMS_ROOT", "")
    if _root and os.path.isdir(_root):
        os.add_dll_directory(_root)
        os.environ["PATH"] = _root + os.pathsep + os.environ.get("PATH", "")
    else:
        print(
            "WARNING: OPENEMS_ROOT is not set to the openEMS install folder; "
            "importing CSXCAD/openEMS may fail on Windows.",
            file=sys.stderr,
        )

import numpy as np

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import C0

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- parameters
PROJECT_NAME = "$PROJECT_NAME"
F0 = $F0              # design / excitation centre frequency [Hz]
F_MIN = $F_MIN        # sweep start [Hz]
F_MAX = $F_MAX        # sweep stop [Hz]
N_FREQ = $N_FREQ      # sweep points

H_TOTAL = $H_TOTAL         # total substrate thickness [m]
EPS_SUB = $EPS_SUB         # substrate relative permittivity
KAPPA_SUB = $KAPPA_SUB     # substrate conductivity [S/m] (loss)
TAN_D_SUB = $TAN_D_SUB     # substrate loss tangent at F0 (reference value)
MU_SUB = $MU_SUB
LOSS_MODEL = "$LOSS_MODEL"  # "kappa" (conductivity), "debye" (dispersive) or "none"
DEBYE_EPS_INF = $DEBYE_EPS_INF        # Debye eps_inf (high-frequency permittivity)
DEBYE_EPS_DELTA = $DEBYE_EPS_DELTA    # Debye pole strength (eps_s - eps_inf)
DEBYE_TAU = $DEBYE_TAU                # Debye relaxation time [s]
EPS0 = 8.8541878128e-12

W_PATCH = $W_PATCH         # patch width along x [m]
L_PATCH = $L_PATCH         # patch length along y [m]
GROUND_X = $GROUND_X       # ground plane size along x [m]
GROUND_Y = $GROUND_Y       # ground plane size along y [m]
GROUND_MARGIN_LAMBDA = $GROUND_MARGIN_LAMBDA   # margin per side, in lambda0
CONDUCTOR_MODEL = "$CONDUCTOR_MODEL"   # metals are ideal PEC: conductor loss is NOT modelled

FEED_X = $FEED_X
FEED_Y = $FEED_Y
FEED_INSET = $FEED_INSET
FEED_LINE_WIDTH = $FEED_LINE_WIDTH   # microstrip line width [m]; 0 = legacy probe feed
FEED_MODE = "$FEED_MODE"
FEED_Z0 = $FEED_Z0         # port reference impedance [ohm]

MESH_MAX_RES = C0 / F_MAX / $MESH_CELLS_PER_WAVELENGTH
MESH_SUBSTRATE_CELLS = $MESH_SUBSTRATE_CELLS
PORT_REFINE = $PORT_REFINE   # refine the mesh around the lumped port (review item A4)
MESH_SMOOTHING = $MESH_SMOOTHING
METAL_EDGE_SNAPPING = $METAL_EDGE_SNAPPING
NUM_THREADS = $NUM_THREADS   # 0 = let openEMS measure and decide, N = force N threads
NF2FF_ENABLED = $NF2FF_ENABLED
NF2FF_FREQS = $NF2FF_FREQS
PML_CELLS = $PML_CELLS
BOUNDARY_MODE = "$BOUNDARY_MODE"
AIRBOX_LAMBDA = $AIRBOX_LAMBDA      # air margin around the structure, per side
AIR_TOP_LAMBDA = $AIR_TOP_LAMBDA    # air margin above the patch
UNIT_CELL = $UNIT_CELL
ELEMENT_PORTS = $ELEMENT_PORTS    # one lumped port per array element (Phase 2 #4)
EXCITE_PORT = int(os.environ.get("OPENANTENNA_EXCITE_PORT", "1"))
MAX_TS = $MAX_TS
END_CRITERIA = $END_CRITERIA

# ---------------------------------------------------------------- FDTD setup
# The excitation must cover the whole sweep; use F0 as centre and half of F0 as
# the Gaussian half-width (the convention used by the openEMS tutorials).
# The published openEMS Windows wheel (0.37.0-rc2) does NOT accept a ``numthreads``
# keyword - it raises "AssertionError: Unknown keyword arguments" - and none of its
# Python methods set a thread count.  Ask for it, then fall back cleanly so the model
# still runs on the official build.  (Yotta review: P0 regression, found by running a
# generated model against openEMS 0.37.0-rc2.)
try:
    FDTD = openEMS(NrTS=MAX_TS, EndCriteria=END_CRITERIA, numthreads=NUM_THREADS)
    print("THREADS: %s (accepted by this openEMS build)"
          % ("auto" if NUM_THREADS == 0 else str(NUM_THREADS)))
except (TypeError, AssertionError) as _threads_exc:
    FDTD = openEMS(NrTS=MAX_TS, EndCriteria=END_CRITERIA)
    print("THREADS: this openEMS build has no numthreads support (%s); "
          "using the solver default" % type(_threads_exc).__name__)
FDTD.SetGaussExcite(F0, 0.5 * F0)
if BOUNDARY_MODE == "UNIT_CELL":
    # Infinite-array unit cell at broadside: PEC on the x pair, PMC on the y pair, an
    # absorber only in z.  The lateral domain is exactly one element pitch, which the
    # symmetry walls require; an oblique scan angle is NOT representable this way.
    FDTD.SetBoundaryCond(["PEC", "PEC", "PMC", "PMC", "PML_%d" % PML_CELLS, "PML_%d" % PML_CELLS])
    print("BOUNDARY: UNIT_CELL (PEC/PEC/PMC/PMC/PML/PML) - broadside only")
elif BOUNDARY_MODE == "MUR":
    FDTD.SetBoundaryCond(["MUR"] * 6)
else:
    FDTD.SetBoundaryCond(["PML_%d" % PML_CELLS] * 6)
print("BOUNDARY: %s" % ("MUR" if BOUNDARY_MODE == "MUR" else ("UNIT_CELL" if BOUNDARY_MODE == "UNIT_CELL" else "PML_%d" % PML_CELLS)))

CSX = ContinuousStructure()
FDTD.SetCSX(CSX)
mesh = CSX.GetGrid()
mesh.SetDeltaUnit(1.0)   # everything below is in metres

# ---------------------------------------------------------------- loss check
def implied_tan_delta(frequency_hz):
    """tan_delta that KAPPA_SUB actually represents at a given frequency.

    A constant conductivity gives tan_delta(f) = kappa / (2*pi*f*eps0*eps_r),
    so it equals the target value exactly at F0 and drifts as 1/f away from it.
    """
    if KAPPA_SUB <= 0:
        return 0.0
    return KAPPA_SUB / (2.0 * np.pi * frequency_hz * EPS0 * EPS_SUB)


def debye_tan_delta(frequency_hz):
    """tan_delta(f) of the single-pole Debye used when LOSS_MODEL == "debye".

    Unlike the constant-conductivity model this is correct *everywhere*: it rises as f
    below the relaxation and falls as 1/f above it.
    """
    w = 2.0 * np.pi * frequency_hz
    num = w * DEBYE_TAU * DEBYE_EPS_DELTA
    den = DEBYE_EPS_INF * (1.0 + (w * DEBYE_TAU) ** 2) + DEBYE_EPS_DELTA
    return num / den


print("LOSS MODEL: %s" % LOSS_MODEL)
if LOSS_MODEL == "kappa" and KAPPA_SUB > 0:
    print("  target tan_delta at F0 = %.6g" % TAN_D_SUB)
    print(
        "  implied tan_delta at %.4g / %.4g / %.4g Hz: %.6g / %.6g / %.6g"
        % (F_MIN, F0, F_MAX, implied_tan_delta(F_MIN), implied_tan_delta(F0), implied_tan_delta(F_MAX))
    )
    print("  NOTE: constant-sigma approximation; it is exact at F0 only.")
elif LOSS_MODEL == "debye" and DEBYE_EPS_DELTA > 0:
    print(
        "  Debye pole: eps_inf=%.6g  eps_delta=%.6g  tau=%.6g s"
        % (DEBYE_EPS_INF, DEBYE_EPS_DELTA, DEBYE_TAU)
    )
    print(
        "  tan_delta at %.4g / %.4g / %.4g Hz: %.6g / %.6g / %.6g"
        % (F_MIN, F0, F_MAX, debye_tan_delta(F_MIN), debye_tan_delta(F0), debye_tan_delta(F_MAX))
    )
    print("  NOTE: dispersive by construction - no 1/f drift to correct for.")
else:
    print("  lossless substrate (kappa = 0): no dielectric loss in this model.")

# ---------------------------------------------------------------- geometry
if LOSS_MODEL == "debye":
    # Dispersive substrate.  The dispersive classes live in the CSXCAD.CSProperties
    # submodule (not at the CSXCAD top level), SetDispersiveMaterialProperty takes the
    # 0-based pole index *first*, and the property must be registered via AddProperty()
    # or the structure will not write it.
    from CSXCAD import CSProperties as _CSProp

    substrate = _CSProp.CSPropDebyeMaterial(CSX.GetParameterSet(), "substrate")
    substrate.SetDispersionOrder(1)
    substrate.SetDispersiveMaterialProperty(0, eps_delta=DEBYE_EPS_DELTA, eps_relax=DEBYE_TAU)
    substrate.SetMaterialProperty(epsilon=DEBYE_EPS_INF, mue=MU_SUB)
    CSX.AddProperty(substrate)
else:
    substrate = CSX.AddMaterial("substrate", epsilon=EPS_SUB, mue=MU_SUB, kappa=KAPPA_SUB)
substrate.AddBox(
    [-GROUND_X / 2.0, -GROUND_Y / 2.0, -H_TOTAL],
    [GROUND_X / 2.0, GROUND_Y / 2.0, 0.0],
    priority=1,
)

# Metals are modelled as infinitely thin sheets: a degenerate box whose start
# and stop coincide in z.  openEMS snaps such a sheet onto the mesh.  Forcing a
# physical metal thickness here would create ~35 um cells, which collapses the
# FDTD timestep (observed: dt = 6.5e-14 s at 35 um) and wastes hours.
ground = CSX.AddMetal("ground")
ground.AddBox(
    [-GROUND_X / 2.0, -GROUND_Y / 2.0, -H_TOTAL],
    [GROUND_X / 2.0, GROUND_Y / 2.0, -H_TOTAL],
    priority=2,
)

# Radiating elements, one thin sheet per array element.  With a coplanar inset feed the
# patch carries a rectangular notch on the feed edge (review item Y-19), so that element is
# emitted as three sheets; every other element stays a plain rectangle.
ELEMENTS = $ELEMENTS_LITERAL
FEED_IS_LINE = FEED_MODE in ("inset", "edge") and FEED_LINE_WIDTH > 0.0 and FEED_INSET > 0.0
_patch_props = []
for index, (x0, y0) in enumerate(ELEMENTS, start=1):
    patch = CSX.AddMetal("patch_%d" % index)
    if FEED_IS_LINE and index == 1:
        _slot = FEED_LINE_WIDTH / 2.0
        _y_bottom = y0 - L_PATCH / 2.0
        _y_top = y0 + L_PATCH / 2.0
        _y_notch = _y_top - FEED_INSET
        patch.AddBox(
            [x0 - W_PATCH / 2.0, _y_bottom, 0.0], [x0 - _slot, _y_top, 0.0], priority=3
        )
        patch.AddBox(
            [x0 + _slot, _y_bottom, 0.0], [x0 + W_PATCH / 2.0, _y_top, 0.0], priority=3
        )
        patch.AddBox(
            [x0 - _slot, _y_bottom, 0.0], [x0 + _slot, _y_notch, 0.0], priority=3
        )
    else:
        patch.AddBox(
            [x0 - W_PATCH / 2.0, y0 - L_PATCH / 2.0, 0.0],
            [x0 + W_PATCH / 2.0, y0 + L_PATCH / 2.0, 0.0],
            priority=3,
        )
    _patch_props.append(patch)

if METAL_EDGE_SNAPPING:
    # Force mesh lines exactly on the metal edges, as the openEMS patch tutorial
    # does with AddEdges2Grid.  Without it a degenerate (zero-thickness) sheet can
    # be snapped to the neighbouring cell, which changes the *effective* patch
    # size - a candidate for the 4.31 % offset observed against the tutorial.
    FDTD.AddEdges2Grid(dirs="xy", properties=ground, metal_edge_res=MESH_MAX_RES / 2.0)
    for _prop in _patch_props:
        FDTD.AddEdges2Grid(dirs="xy", properties=_prop, metal_edge_res=MESH_MAX_RES / 2.0)
    print("METAL EDGES: snapped to the grid (AddEdges2Grid, res %.3f mm)" % (MESH_MAX_RES / 2.0 * 1e3))

# Feed realisation, two honest options:
#   * FEED_IS_LINE: a microstrip line on the substrate that enters the patch notch - the
#     coplanar inset the synthesis formula actually describes (review item Y-19).  The port
#     sits at the outer end of that line, so the modelled feed matches what gets built.
#   * otherwise: a vertical lumped port from the ground plane to the patch, i.e. a
#     probe/coax feed.  FEED_Y is shifted by the inset depth, so feed_mode="inset" then only
#     moves the probe; that model cannot validate the inset formula.
#
# ``edges2grid`` snaps the port box onto the mesh; without it openEMS reports
# "Unused primitive (type: Box) ... port_excite", the port never excites and every
# S11 value comes out NaN.
# NOTE: a real NxM array also needs a feed network and one port per element (or a
# proper corporate-feed model).  Phase 1 models ONE port only.
print("CONDUCTOR: %s (conductor loss not modelled)" % CONDUCTOR_MODEL)
if ELEMENT_PORTS:
    ELEMENT_PORTS_OBJS = []
    # Phase 2 #4: one port per element, so a coupling matrix can be extracted.  Which port
    # is driven comes from the environment, so ONE deck yields every row of the S-matrix by
    # being run once per port - no per-run editing, and no risk of the decks drifting apart.
    if FEED_IS_LINE:
        raise SystemExit(
            "element_ports=True with a printed feed line is not supported yet: per-element "
            "lines belong to the corporate-feed work (Phase 2 #5)"
        )
    # Keep every port object.  Without this `port` is never bound and main() dies with
    # NameError before it can write a single result - found by static audit, and the
    # rendered-text tests cannot see it, hence the regression test shipped with this patch.
    for index, (x0, y0) in enumerate(ELEMENTS, start=1):
        ELEMENT_PORTS_OBJS.append(
            FDTD.AddLumpedPort(
                index,
                FEED_Z0,
                [x0 + FEED_X, y0 + FEED_Y, -H_TOTAL],
                [x0 + FEED_X, y0 + FEED_Y, 0.0],
                "z",
                1.0 if index == EXCITE_PORT else 0.0,
                priority=5,
                edges2grid="xy",
            )
        )
    port = ELEMENT_PORTS_OBJS[0]
    print(
        "PORTS: %d element ports (probe feed); exciting port %d "
        "- set OPENANTENNA_EXCITE_PORT to excite another"
        % (len(ELEMENTS), EXCITE_PORT)
    )
else:
    if FEED_IS_LINE:
        _feed_line = CSX.AddMetal("feed_line")
        _feed_line.AddBox(
            [FEED_X - FEED_LINE_WIDTH / 2.0, FEED_Y - FEED_INSET, 0.0],
            [FEED_X + FEED_LINE_WIDTH / 2.0, GROUND_Y / 2.0, 0.0],
            priority=4,
        )
        if METAL_EDGE_SNAPPING:
            FDTD.AddEdges2Grid(
                dirs="xy", properties=_feed_line, metal_edge_res=MESH_MAX_RES / 2.0
            )
        _port_y = GROUND_Y / 2.0 - 2.0 * MESH_MAX_RES
        print(
            "FEED: coplanar inset line (Y-19), width %.3f mm, inset %.3f mm, port at y = %.3f mm"
            % (FEED_LINE_WIDTH * 1e3, FEED_INSET * 1e3, _port_y * 1e3)
        )
    else:
        _port_y = FEED_Y
        print("FEED: vertical lumped port (probe); inset depth = %.3f mm" % (FEED_INSET * 1e3))
    port = FDTD.AddLumpedPort(
        1,
        FEED_Z0,
        [FEED_X, _port_y, -H_TOTAL],
        [FEED_X, _port_y, 0.0],
        "z",
        1.0,
        priority=5,
        edges2grid="xy",
    )
print(
    "GROUND: %.3f x %.3f mm (margin %.3f lambda0 per side; the ground plane is part "
    "of the radiating structure - review item N-01)"
    % (GROUND_X * 1e3, GROUND_Y * 1e3, GROUND_MARGIN_LAMBDA)
)

# ---------------------------------------------------------------- meshing
# The simulation domain must contain air above and around the structure,
# otherwise the absorbing boundary has nothing to absorb: openEMS then reports
# "Not enough lines in direction 2, resetting to PEC" and the run is a closed
# metal box rather than a radiating antenna.
lambda_min = C0 / F_MAX
if BOUNDARY_MODE == "UNIT_CELL":
    # the symmetry walls sit exactly on the cell boundary, so no lateral air margin
    DOM_X = GROUND_X / 2.0
    DOM_Y = GROUND_Y / 2.0
else:
    DOM_X = GROUND_X / 2.0 + AIRBOX_LAMBDA * lambda_min
    DOM_Y = GROUND_Y / 2.0 + AIRBOX_LAMBDA * lambda_min
DOM_Z_BOT = -(H_TOTAL + AIRBOX_LAMBDA * lambda_min)
DOM_Z_TOP = AIR_TOP_LAMBDA * lambda_min

CSX.AddMaterial("air").AddBox(
    [-DOM_X, -DOM_Y, DOM_Z_BOT], [DOM_X, DOM_Y, DOM_Z_TOP], priority=0
)

# Structure edges are added as explicit mesh lines so that the substrate,
# patch and feed land exactly on cell boundaries; the free-space regions then
# get a coarser staircase which SmoothMeshLines refines.
mesh.AddLine("x", np.linspace(-DOM_X, DOM_X, 25))
mesh.AddLine("y", np.linspace(-DOM_Y, DOM_Y, 25))
mesh.AddLine("x", [-W_PATCH / 2.0, W_PATCH / 2.0, FEED_X])
mesh.AddLine("y", [-L_PATCH / 2.0, L_PATCH / 2.0, FEED_Y])
for x0, y0 in ELEMENTS:
    mesh.AddLine("x", [x0 - W_PATCH / 2.0, x0 + W_PATCH / 2.0])
    mesh.AddLine("y", [y0 - L_PATCH / 2.0, y0 + L_PATCH / 2.0])
mesh.AddLine("z", np.linspace(-H_TOTAL, 0.0, MESH_SUBSTRATE_CELLS + 1))
mesh.AddLine("z", [DOM_Z_BOT, -H_TOTAL, 0.0, DOM_Z_TOP])
mesh.AddLine("z", np.linspace(0.0, DOM_Z_TOP, 9))
mesh.AddLine("z", np.linspace(DOM_Z_BOT, -H_TOTAL, 5))

if PORT_REFINE:
    # Refine the mesh around the feed.  The lumped port feeds a load across the
    # substrate; if the lateral cell there is the coarse free-space cell, the
    # excitation is badly discretised and the port contributes series inductance
    # to the model - a candidate for the residual construction bias
    # (Yotta review item A4).  The refinement uses the substrate cell size.
    _port_cell = H_TOTAL / MESH_SUBSTRATE_CELLS
    _port_half = 2.0 * _port_cell
    mesh.AddLine("x", np.linspace(FEED_X - _port_half, FEED_X + _port_half, 5))
    mesh.AddLine("y", np.linspace(FEED_Y - _port_half, FEED_Y + _port_half, 5))
    print(
        "PORT REFINE: %.4f mm cells over %.4f mm around the feed"
        % (_port_cell * 1e3, 2.0 * _port_half * 1e3)
    )

if FEED_IS_LINE:
    # A printed feed line needs cells *across* it.  At the default resolution
    # (MESH_MAX_RES = c/(F_MAX * cells_per_lambda)) a 5.1 mm line on PTFE is less than one
    # cell wide, so the line would be a stair-step artifact and any probe-vs-line
    # comparison would measure the mesh, not the feed.  Four cells across the line, and
    # four along the notch depth, keep the feed discretised like the port already is.
    _line_cells = 4
    mesh.AddLine(
        "x",
        np.linspace(
            FEED_X - FEED_LINE_WIDTH / 2.0, FEED_X + FEED_LINE_WIDTH / 2.0, _line_cells + 1
        ),
    )
    _patch_top = ELEMENTS[0][1] + L_PATCH / 2.0
    mesh.AddLine("y", np.linspace(FEED_Y, _patch_top, 5))
    print(
        "FEED MESH: %d cells across the %.3f mm line (%.3f mm each)"
        % (_line_cells, FEED_LINE_WIDTH * 1e3, FEED_LINE_WIDTH / _line_cells * 1e3)
    )

mesh.SmoothMeshLines("all", MESH_MAX_RES, MESH_SMOOTHING)

print(
    "DOMAIN: x=[%.1f, %.1f] y=[%.1f, %.1f] z=[%.1f, %.1f] mm"
    % (
        -DOM_X * 1e3, DOM_X * 1e3,
        -DOM_Y * 1e3, DOM_Y * 1e3,
        DOM_Z_BOT * 1e3, DOM_Z_TOP * 1e3,
    )
)

# Near-to-far-field recording box.  It MUST be created after the mesh is complete.
# Explicit start/stop bounds are passed on purpose: the automatic bounds require more
# than pml_cells+1 mesh lines on each side of the domain, which this mesh does not
# have, and openEMS then raises "not enough lines in some direction".  The box is
# placed just outside the ground plane and inside the absorber.
NF_CLEAR = 0.05 * lambda_min
# Only the DFT at these frequencies is recorded.  Without the ``frequency`` argument
# the box records the raw time series on all six faces, which turns a minutes-long
# run into an hours-long, I/O-bound one (observed: a single patch case still writing
# nf2ff_*.h5 after 26 minutes).
NF_FREQS = np.linspace(F_MIN, F_MAX, NF2FF_FREQS)
nf2ff = None
if NF2FF_ENABLED:
    nf2ff = FDTD.CreateNF2FFBox(
        name="nf2ff",
        start=[-GROUND_X / 2.0 - NF_CLEAR, -GROUND_Y / 2.0 - NF_CLEAR, -H_TOTAL - NF_CLEAR],
        stop=[GROUND_X / 2.0 + NF_CLEAR, GROUND_Y / 2.0 + NF_CLEAR, DOM_Z_TOP - NF_CLEAR],
        frequency=NF_FREQS,
    )
    print(
        "NF2FF: box x=[%.1f, %.1f] y=[%.1f, %.1f] z=[%.1f, %.1f] mm"
        % (
            (-GROUND_X / 2.0 - NF_CLEAR) * 1e3, (GROUND_X / 2.0 + NF_CLEAR) * 1e3,
            (-GROUND_Y / 2.0 - NF_CLEAR) * 1e3, (GROUND_Y / 2.0 + NF_CLEAR) * 1e3,
            (-H_TOTAL - NF_CLEAR) * 1e3, (DOM_Z_TOP - NF_CLEAR) * 1e3,
        )
    )


def main():
    sim_path = os.path.join(HERE, "openems_run")
    FDTD.Run(sim_path, verbose=3, cleanup=True)

    freqs = np.linspace(F_MIN, F_MAX, N_FREQ)

    if ELEMENT_PORTS:
        # Phase 2 #4: dump EVERY port, not only the driven one.  One run yields a full
        # column of the S-matrix, S_ij = uf_ref(i) / uf_inc(j), and running the same deck
        # once per driven port assembles the whole matrix.
        driven = None
        for index, element_port in enumerate(ELEMENT_PORTS_OBJS, start=1):
            element_port.CalcPort(sim_path, freqs, FEED_Z0)
            port_path = os.path.join(HERE, "port_%d.csv" % index)
            with open(port_path, "w", newline="", encoding="utf-8") as handle:
                writer = csv.writer(handle)
                writer.writerow(["freq_hz", "uf_inc_re", "uf_inc_im", "uf_ref_re", "uf_ref_im"])
                for frequency, inc, ref in zip(freqs, element_port.uf_inc, element_port.uf_ref):
                    writer.writerow(
                        ["%.6e" % frequency, "%.9e" % inc.real, "%.9e" % inc.imag,
                         "%.9e" % ref.real, "%.9e" % ref.imag]
                    )
            if index == EXCITE_PORT:
                driven = element_port
        if driven is None:
            raise SystemExit(
                "OPENANTENNA_EXCITE_PORT=%d is outside the %d element ports"
                % (EXCITE_PORT, len(ELEMENT_PORTS_OBJS))
            )
        port = driven
        print(
            "PORTS: wrote %d per-port files; driven port %d"
            % (len(ELEMENT_PORTS_OBJS), EXCITE_PORT)
        )

    # The port object that carries s11.csv must be resolved per branch: with element ports the
    # single-port variable below is never bound, and the unconditional use of it here is what
    # killed the B2 `probe` arms AFTER a full 400k-step FDTD (UnboundLocalError, 3230 s per arm,
    # no s11.csv).  Text tests cannot see an unbound local - only running the deck can - so the
    # guard below is deliberately explicit about which port is being read.
    if ELEMENT_PORTS:
        if not 1 <= EXCITE_PORT <= len(ELEMENT_PORTS_OBJS):
            raise SystemExit(
                "OPENANTENNA_EXCITE_PORT=%d is outside 1..%d"
                % (EXCITE_PORT, len(ELEMENT_PORTS_OBJS))
            )
        _s11_port = ELEMENT_PORTS_OBJS[EXCITE_PORT - 1]
    else:
        _s11_port = port
    _s11_port.CalcPort(sim_path, freqs, FEED_Z0)
    s11 = _s11_port.uf_ref / _s11_port.uf_inc

    out_path = os.path.join(HERE, "s11.csv")
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("freq_hz,s11_re,s11_im\\n")
        for frequency, value in zip(freqs, s11):
            handle.write("%.6e,%.9e,%.9e\\n" % (frequency, value.real, value.imag))

    with open(os.path.join(HERE, "run_summary.json"), "w", encoding="utf-8") as handle:
        json.dump(
            {
                "solver": "openEMS",
                "project": PROJECT_NAME,
                "f_min_hz": float(F_MIN),
                "f_max_hz": float(F_MAX),
                "n_freq": int(N_FREQ),
                "s11_csv": out_path,
                "note": "generated by OpenAntenna Studio; verify before trusting",
            },
            handle,
            indent=2,
        )
    print("wrote", out_path)

    if nf2ff is not None:
        # --- far field -------------------------------------------------------
        far_freqs = NF_FREQS  # must be the same array the box was created with
        theta_deg = np.arange(0.0, 181.0, 2.0)
        phi_deg = np.arange(0.0, 361.0, 5.0)
        print(
            "NF2FF: computing the far field on a %dx%d grid at %d frequencies"
            % (len(theta_deg), len(phi_deg), len(far_freqs))
        )
        res = nf2ff.CalcNF2FF(sim_path, far_freqs, theta_deg, phi_deg, outfile="nf2ff.h5")

        # Accepted power from the port: P_acc = 0.5*(|uf_inc|^2 - |uf_ref|^2)/Z0.
        # This is what separates radiation efficiency from total efficiency.
        p_acc = 0.5 * (np.abs(port.uf_inc) ** 2 - np.abs(port.uf_ref) ** 2) / FEED_Z0

        summary_path = os.path.join(HERE, "nf2ff_summary.csv")
        with open(summary_path, "w", encoding="utf-8") as handle:
            handle.write("freq_hz,directivity_lin,directivity_dbi,prad_w,p_acc_w,eta_rad")
            for n, frequency in enumerate(res.freq):
                d = float(res.Dmax[n])
                prad = float(res.Prad[n])
                accepted = float(p_acc[n]) if n < len(p_acc) else float("nan")
                eta = prad / accepted if accepted > 0 else float("nan")
                handle.write(
                    "\\n%.6e,%.6e,%.6e,%.9e,%.9e,%.9e"
                    % (frequency, d, 10.0 * np.log10(max(d, 1e-12)), prad, accepted, eta)
                )
        print("NF2FF: wrote", summary_path)

        # Radiation pattern at the frequency closest to the design centre.
        idx = int(np.argmin(np.abs(np.array(res.freq) - F0)))
        pattern_path = os.path.join(HERE, "nf2ff_pattern.csv")
        e_norm = res.E_norm[idx]
        with open(pattern_path, "w", encoding="utf-8") as handle:
            handle.write("theta_deg,phi_deg,e_norm\\n")
            for i, theta in enumerate(np.rad2deg(res.theta)):
                for j, phi in enumerate(np.rad2deg(res.phi)):
                    handle.write("%.3f,%.3f,%.9e\\n" % (theta, phi, e_norm[i, j]))
        print("NF2FF: wrote %s (pattern at %.4f GHz)" % (pattern_path, res.freq[idx] / 1e9))


if __name__ == "__main__":
    main()
'''
)


class OpenEMSSolver(SolverAdapter):
    """Adapter that renders and (when possible) runs an openEMS model."""

    name = "openems"
    script_name = "sim.py"
    project_name = "project.json"
    results_name = "s11.csv"

    def __init__(
        self,
        mesh_cells_per_wavelength: int = 15,
        substrate_cells: int = 8,
        air_margin_lambda: float = 0.80,
        air_top_lambda: float = 0.80,
        loss_model: str = "kappa",
        ground_margin_lambda: float = 0.25,
        boundary: str = "PML",
        pml_cells: int = 8,
        mesh_smoothing_ratio: float = 1.4,
        metal_edge_snapping: bool = True,
        # Off by default (backlog A2 / review item R-7): the box adds a far-field pass to
        # every run -- and before the DFT-only recording change it wrote 12 near-field
        # HDF5 files during the FDTD loop -- for data that S11 work never reads.  Opt in
        # with ``nf2ff=True`` (CLI: ``--nf2ff``); the manifest always records the setting.
        nf2ff: bool = False,
        nf2ff_frequencies: int = 5,
        unit_cell: bool = False,
        #: Phase 2 #4: one lumped port per array element.  The same deck produces every row
        #: of the coupling matrix, because which port is driven comes from the environment
        #: (``OPENANTENNA_EXCITE_PORT``) rather than from the file.
        element_ports: bool = False,
        numthreads: int = 0,
        port_refine: bool = True,
        max_timesteps: int = 400000,
        end_criteria: float = 1e-4,
    ) -> None:
        """Create an adapter with explicit mesh-resolution controls.

        The defaults are a *fast* setting, not a converged one.  Mesh
        convergence must be established per design by re-running with finer
        values; nothing in this package has been calibrated yet.

        The air margins default to 0.80 lambda0 because the absorbing boundary
        needs at least ``pml_cells`` cells of clearance: at 15 cells/wavelength a
        0.20 lambda0 margin leaves only ~3 cells, and openEMS then rejects the
        near-to-far-field box ("not enough lines in some direction") and applies
        the PML over the structure.  The earlier air-margin A/B showed that a
        larger domain leaves the resonance unchanged and converges in *fewer*
        timesteps, so this is a strict improvement.
        """
        if mesh_cells_per_wavelength < 4:
            raise ValueError("mesh_cells_per_wavelength must be >= 4")
        if substrate_cells < 2:
            raise ValueError("substrate_cells must be >= 2")
        if air_margin_lambda <= 0 or air_top_lambda <= 0:
            raise ValueError("air margins must be > 0")
        if loss_model not in ("kappa", "debye", "none"):
            raise ValueError("loss_model must be 'kappa', 'debye' or 'none'")
        if ground_margin_lambda <= 0:
            raise ValueError("ground_margin_lambda must be > 0")
        if boundary not in ("PML", "MUR"):
            raise ValueError("boundary must be 'PML' or 'MUR'")
        if pml_cells < 2:
            raise ValueError("pml_cells must be >= 2")
        if mesh_smoothing_ratio <= 1.0:
            raise ValueError("mesh_smoothing_ratio must be > 1")
        if max_timesteps < 100:
            raise ValueError("max_timesteps must be >= 100")
        if end_criteria <= 0:
            raise ValueError("end_criteria must be > 0")
        self.boundary = boundary
        self.pml_cells = int(pml_cells)
        self.mesh_smoothing_ratio = float(mesh_smoothing_ratio)
        self.metal_edge_snapping = bool(metal_edge_snapping)
        if nf2ff_frequencies < 1:
            raise ValueError("nf2ff_frequencies must be >= 1")
        self.nf2ff = bool(nf2ff)
        self.nf2ff_frequencies = int(nf2ff_frequencies)
        # Unit cell for an infinite array at broadside.  openEMS's Python API exposes
        # no periodic boundary condition, so this uses symmetry walls instead: PEC on
        # one lateral pair, PMC on the other.  That is exact at broadside and *cannot*
        # represent an oblique scan angle - say so rather than pretending otherwise.
        self.unit_cell = bool(unit_cell)
        self.element_ports = bool(element_ports)
        if numthreads < 0:
            raise ValueError("numthreads must be >= 0 (0 lets openEMS decide)")
        self.numthreads = int(numthreads)
        self.port_refine = bool(port_refine)
        self.max_timesteps = int(max_timesteps)
        self.end_criteria = float(end_criteria)
        self.ground_margin_lambda = float(ground_margin_lambda)
        self.loss_model = loss_model
        self.last_kappa = 0.0
        self.last_debye = (0.0, 0.0, 0.0)
        self.last_reference_frequency_hz = None
        self.mesh_cells_per_wavelength = int(mesh_cells_per_wavelength)
        self.substrate_cells = int(substrate_cells)
        self.air_margin_lambda = float(air_margin_lambda)
        self.air_top_lambda = float(air_top_lambda)

    # ----------------------------------------------------------------- probe
    @staticmethod
    def resolve_root() -> Optional[str]:
        """Locate the openEMS installation folder (native DLLs + executables).

        Resolution order: ``OPENEMS_ROOT`` environment variable, then the
        folder containing an ``openEMS`` executable on PATH.
        """
        env = os.environ.get("OPENEMS_ROOT")
        if env and Path(env).is_dir():
            return str(Path(env))
        exe = shutil.which("openEMS") or shutil.which("openems")
        if exe:
            return str(Path(exe).parent)
        return None

    def available(self) -> SolverStatus:
        root = self.resolve_root()
        binary = None
        if root:
            for candidate in ("openEMS.exe", "openEMS"):
                path = Path(root) / candidate
                if path.exists():
                    binary = str(path)
                    break
        binary = binary or shutil.which("openEMS") or shutil.which("openems")
        have_csxcad = importlib_util.find_spec("CSXCAD") is not None
        have_openems_py = importlib_util.find_spec("openEMS") is not None

        missing = []
        if binary is None:
            missing.append("openEMS executable (not on PATH)")
        if not have_csxcad:
            missing.append("python module 'CSXCAD'")
        if not have_openems_py:
            missing.append("python module 'openEMS'")

        if missing:
            return SolverStatus(
                name=self.name,
                available=False,
                detail=(
                    "openEMS cannot be executed here; missing: " + ", ".join(missing)
                    + ". Model generation still works. Set OPENEMS_ROOT to the "
                    "folder that contains openEMS.exe / CSXCAD.dll."
                ),
                binary_path=binary,
            )
        return SolverStatus(
            name=self.name,
            available=True,
            detail=(
                "openEMS executable and CSXCAD/openEMS python modules found"
                + (f" (root: {root})" if root else "")
                + "."
            ),
            binary_path=binary,
        )

    # --------------------------------------------------------------- prepare
    def render_script(self, project: Project) -> str:
        """Render the openEMS python script for ``project`` (no I/O)."""
        layers = project.substrate.dielectric_layers() or project.substrate.layers
        if len(layers) > 1:
            raise ValueError(
                "the Phase 1 openEMS generator supports a single dielectric layer; "
                f"got {len(layers)}. Collapse the stackup to an effective medium first."
            )
        layer = layers[0]

        material_name = layer.material
        epsilon_r = 1.0
        tan_delta = 0.0
        mu_r = 1.0
        try:
            from ..materials.library import get_material

            material = get_material(material_name)
            epsilon_r = float(material.epsilon_r)
            tan_delta = float(material.tan_delta)
            mu_r = float(material.mu_r)
        except KeyError:
            raise ValueError(
                f"unknown substrate material {material_name!r}; define it in the "
                "material library before generating solver input"
            ) from None

        # Dielectric loss.  A constant conductivity reproduces the requested loss
        # tangent exactly at the reference frequency (the sweep centre) and drifts
        # as 1/f away from it; the generated script prints the implied tan_delta
        # at the sweep edges so that drift is visible rather than hidden.
        # loss_model="none" produces a lossless substrate.
        if self.loss_model == "none" or tan_delta <= 0.0:
            kappa_sub = 0.0
        else:
            kappa_sub = (
                2.0 * math.pi * project.sweep.center_hz * EPS0 * epsilon_r * tan_delta
            )
        self.last_kappa = kappa_sub
        self.last_reference_frequency_hz = project.sweep.center_hz

        # Dispersive (Debye) equivalent of the same loss level.  If the material carries a
        # Debye description in the library we use it verbatim; otherwise a single pole is
        # placed at omega*tau = 1 at the reference frequency with
        # eps_delta = 2*tan_delta*eps_r, which reproduces the requested tan(delta) there
        # (from tan(d) = (delta/2) / (eps_inf + delta/2)).
        eps_inf_d, eps_delta_d, tau_d = epsilon_r, 0.0, 0.0
        if self.loss_model == "debye" and tan_delta > 0.0:
            spec = material.dispersion if getattr(material, "dispersion", None) else None
            if spec and spec.get("model") == "debye" and "delta_eps" in spec and "tau_s" in spec:
                eps_inf_d = float(spec.get("eps_inf", epsilon_r))
                eps_delta_d = float(spec["delta_eps"])
                tau_d = float(spec["tau_s"])
            else:
                eps_inf_d = epsilon_r
                eps_delta_d = 2.0 * tan_delta * epsilon_r
                tau_d = 1.0 / (2.0 * math.pi * project.sweep.center_hz)
        self.last_debye = (eps_inf_d, eps_delta_d, tau_d)

        design = synthesize_patch(
            frequency_hz=project.sweep.center_hz,
            epsilon_r=epsilon_r,
            height_m=layer.thickness_m,
            feed_mode=project.patch.feed_mode,
        )
        width = project.patch.width_m or design.width_m
        length = project.patch.length_m or design.length_m
        # The ground plane must cover the whole radiating aperture.  Sizing it from a single
        # patch is right for a 1x1 (and unchanged there), but a 4x4 at 0.5 lambda0 spans about
        # 2 lambda0: elements would hang off the ground and the model would be physically
        # wrong before the solver ever ran.  Computed from the array configuration rather than
        # from ``layout`` (which is built further down and does not exist yet here).
        _lam0 = C0 / project.sweep.center_hz
        span_x = (project.array.nx - 1) * project.array.spacing_x_lambda0 * _lam0 + width
        span_y = (project.array.ny - 1) * project.array.spacing_y_lambda0 * _lam0 + length
        if project.array.nx * project.array.ny > 1:
            print(
                "GROUND: array footprint %.1f x %.1f mm (%d elements) - sized from the "
                "layout, not from one patch"
                % (span_x * 1e3, span_y * 1e3, project.array.nx * project.array.ny)
            )
        ground_x, ground_y = ground_plane_size(
            span_x,
            span_y,
            project.sweep.center_hz,
            margin_lambda=self.ground_margin_lambda,
        )

        layout = build_array_layout(project.array, project.sweep.center_hz, design)

        boundary_mode = self.boundary
        if self.unit_cell:
            # One element in a cell whose lateral size is exactly one element pitch.
            lam0 = C0 / project.sweep.center_hz
            ground_x = project.array.spacing_x_lambda0 * lam0
            ground_y = project.array.spacing_y_lambda0 * lam0
            layout.positions_m = [(0.0, 0.0)]
            boundary_mode = "UNIT_CELL"

        if project.patch.feed_mode == "inset":
            inset = project.patch.feed_inset_m or design.inset_depth_m
            feed_y = length / 2.0 - inset
            feed_x = 0.0
        elif project.patch.feed_mode == "edge":
            feed_x = 0.0
            feed_y = length / 2.0
        elif project.patch.feed_mode == "probe":
            feed_x = 0.0
            feed_y = 0.0
        else:  # corporate feed network is a Phase 2 feature
            feed_x = 0.0
            feed_y = length / 2.0

        conductor_model = "PEC"

        def fmt(value: float) -> str:
            return f"{value:.10g}"

        # One source of truth for the resolved feed-line width (three states: None = let the
        # synthesis decide, 0.0 = probe, >0 = explicit).
        resolved_line_width = (
            design.feed_line_width_m
            if project.patch.feed_line_width_m is None
            else project.patch.feed_line_width_m
        )
        if self.element_ports and resolved_line_width:
            raise ValueError(
                "element_ports=True cannot be combined with a printed feed line yet: "
                "per-element lines belong to the corporate-feed work (Phase 2 #5). "
                "Use feed_line_width_m=0.0 for the probe-style element ports."
            )

        return _SCRIPT_TEMPLATE.substitute(
            VERSION=GENERATOR_VERSION,
            PROJECT_NAME=project.name,
            F0=fmt(project.sweep.center_hz),
            F_MIN=fmt(project.sweep.start_hz),
            F_MAX=fmt(project.sweep.stop_hz),
            N_FREQ=project.sweep.points,
            H_TOTAL=fmt(project.substrate.total_thickness_m),
            EPS_SUB=fmt(epsilon_r),
            KAPPA_SUB=fmt(kappa_sub),
            TAN_D_SUB=fmt(tan_delta),
            MU_SUB=fmt(mu_r),
            LOSS_MODEL=self.loss_model,
            DEBYE_EPS_INF=fmt(eps_inf_d),
            DEBYE_EPS_DELTA=fmt(eps_delta_d),
            DEBYE_TAU=fmt(tau_d),
            W_PATCH=fmt(width),
            L_PATCH=fmt(length),
            GROUND_X=fmt(ground_x),
            GROUND_Y=fmt(ground_y),
            GROUND_MARGIN_LAMBDA=fmt(self.ground_margin_lambda),
            CONDUCTOR_MODEL=conductor_model,
            FEED_X=fmt(feed_x),
            FEED_Y=fmt(feed_y),
            FEED_INSET=fmt(project.patch.feed_inset_m or design.inset_depth_m),
            FEED_LINE_WIDTH=fmt(resolved_line_width),
            FEED_MODE=project.patch.feed_mode,
            FEED_Z0=fmt(50.0),
            MESH_CELLS_PER_WAVELENGTH=self.mesh_cells_per_wavelength,
            MESH_SUBSTRATE_CELLS=self.substrate_cells,
            MESH_SMOOTHING=fmt(self.mesh_smoothing_ratio),
            METAL_EDGE_SNAPPING="True" if self.metal_edge_snapping else "False",
            NF2FF_ENABLED="True" if self.nf2ff else "False",
            NF2FF_FREQS=self.nf2ff_frequencies,
            UNIT_CELL="True" if self.unit_cell else "False",
            ELEMENT_PORTS="True" if self.element_ports else "False",
            NUM_THREADS=self.numthreads,
            PORT_REFINE="True" if self.port_refine else "False",
            PML_CELLS=self.pml_cells,
            BOUNDARY_MODE=self.boundary if not self.unit_cell else "UNIT_CELL",
            AIRBOX_LAMBDA=fmt(self.air_margin_lambda),
            AIR_TOP_LAMBDA=fmt(self.air_top_lambda),
            MAX_TS=self.max_timesteps,
            END_CRITERIA=fmt(self.end_criteria),
            ELEMENTS_LITERAL=repr(
                [[float(x), float(y)] for x, y in layout.positions_m]
            ),
        )

    def prepare(self, project: Project, rundir: str | Path) -> Path:
        run_path = Path(rundir)
        run_path.mkdir(parents=True, exist_ok=True)
        (run_path / self.project_name).write_text(project.to_json() + "\n", encoding="utf-8")
        (run_path / self.script_name).write_text(self.render_script(project), encoding="utf-8")

        warnings = project.check()
        lambda_min = C0 / project.sweep.stop_hz

        # Self-describing runs: record the substrate that was actually used, so a
        # stored result can be re-analysed without the material library that created
        # it (an analyser reading project.json only sees a material *name*).
        layers = project.substrate.dielectric_layers() or project.substrate.layers
        layer = layers[0]
        substrate_info: Dict[str, Any] = {
            "material": layer.material,
            "thickness_m": layer.thickness_m,
        }
        try:
            material = get_material(layer.material)
            substrate_info.update(
                {
                    "epsilon_r": material.epsilon_r,
                    "mu_r": material.mu_r,
                    "tan_delta": material.tan_delta,
                    "conductivity_s_per_m": material.conductivity_s_per_m,
                }
            )
        except KeyError:
            substrate_info["note"] = "material not found in the built-in material library"

        meta = {
            "solver": self.name,
            "generator_version": GENERATOR_VERSION,
            "project": project.name,
            "verified": False,
            "substrate": substrate_info,
            "conductor_model": "PEC (ideal; conductor loss is not modelled) - review item Y-03",
            "ground_margin_lambda": self.ground_margin_lambda,
            "boundary": self.boundary,
            "pml_cells": self.pml_cells,
            "mesh_smoothing_ratio": self.mesh_smoothing_ratio,
            "metal_edge_snapping": self.metal_edge_snapping,
            "nf2ff": self.nf2ff,
            "nf2ff_frequencies": self.nf2ff_frequencies,
            "element_ports": self.element_ports,
            "unit_cell": self.unit_cell,
            "numthreads": self.numthreads,
            "max_timesteps": self.max_timesteps,
            "end_criteria": self.end_criteria,
            "mesh": {
                "cells_per_wavelength": self.mesh_cells_per_wavelength,
                "substrate_cells": self.substrate_cells,
                "port_refine": self.port_refine,
                "air_margin_lambda": self.air_margin_lambda,
                "air_top_lambda": self.air_top_lambda,
                "air_margin_m": self.air_margin_lambda * lambda_min,
                "free_space_to_pml_m": self.air_margin_lambda * lambda_min,
                "pml_clearance_cells": self.air_margin_lambda * self.mesh_cells_per_wavelength,
                "pml_cells": self.pml_cells,
                "pml_thickness_m": self.pml_cells * lambda_min / self.mesh_cells_per_wavelength,
                "converged": False,
                "note": (
                    "free_space_to_pml_m is the nominal gap between the ground-plane "
                    "edge and the absorbing boundary; it is recorded so this quantity "
                    "can be checked instead of guessed (review item Y-18)"
                ),
            },
            "dielectric_loss": {
                "model": self.loss_model,
                "kappa_s_per_m": self.last_kappa,
                "reference_frequency_hz": self.last_reference_frequency_hz,
                "note": (
                    "constant-conductivity equivalent; exact at the reference "
                    "frequency only"
                    if self.loss_model == "kappa"
                    else "lossless substrate"
                ),
            },
            "verification_note": (
                "generated only; never executed against a real openEMS runtime in the "
                "environment where this file was produced"
            ),
            "warnings": warnings,
            "files": [self.script_name, self.project_name],
        }
        (run_path / "run_manifest.json").write_text(
            json.dumps(meta, indent=2) + "\n", encoding="utf-8"
        )
        return run_path.resolve()

    # ------------------------------------------------------------------- run
    def run(
        self,
        rundir: str | Path,
        timeout_s: Optional[float] = None,
        on_progress: Optional[Callable[[Any], None]] = None,
    ) -> SolverRun:
        run_path = Path(rundir)
        status = self.available()
        if not status.available:
            raise SolverUnavailableError(
                f"{status.detail} Run the generated script on a machine that has "
                f"openEMS/CSXCAD installed: python {run_path / self.script_name}"
            )
        script = run_path / self.script_name
        if not script.exists():
            raise FileNotFoundError(f"{script} not found; call prepare() first")

        env = dict(os.environ)
        root = self.resolve_root()
        if root:
            env["OPENEMS_ROOT"] = root
            env["PATH"] = root + os.pathsep + env.get("PATH", "")
        # ``-u`` is required, not cosmetic: the generated script prints progress lines,
        # and a block-buffered child would deliver them in 4 KB bursts hours apart, so
        # the console log stayed empty while the run was clearly alive.
        run = self._execute(
            [sys.executable, "-u", str(script)],
            run_path,
            timeout_s,
            env=env,
            progress_path=run_path / "progress.json",
            total_steps=getattr(self, "max_timesteps", None),
            echo_progress=True,
            on_progress=on_progress,
        )
        # Persist the solver log next to the results: convergence can only be
        # judged from it, and without it a run cannot be audited (review item N-02).
        (run_path / "run.stdout.log").write_text(run.log or "", encoding="utf-8")
        return run

    # --------------------------------------------------------------- results
    def parse_results(self, rundir: str | Path) -> Dict[str, Any]:
        run_path = Path(rundir)
        csv_path = run_path / self.results_name
        if not csv_path.exists():
            raise FileNotFoundError(
                f"{csv_path} not found; the solver has not produced results yet "
                "(expected columns: freq_hz,s11_re,s11_im)"
            )
        frequencies = []
        reals = []
        imags = []
        for index, line in enumerate(csv_path.read_text(encoding="utf-8").splitlines()):
            line = line.strip()
            if not line:
                continue
            if index == 0 and line.lower().startswith("freq"):
                continue
            parts = line.split(",")
            if len(parts) < 3:
                raise ValueError(f"unexpected row in {csv_path.name}: {line!r}")
            frequencies.append(float(parts[0]))
            reals.append(float(parts[1]))
            imags.append(float(parts[2]))
        if not frequencies:
            raise ValueError(f"no data rows in {csv_path}")

        from ..postproc.sparams import S11Trace, vswr_from_gamma

        trace = S11Trace(frequencies, [complex(r, i) for r, i in zip(reals, imags)])
        bands = trace.bandwidth_below(-10.0)
        refined_hz, grid_step_hz, dip_curvature = trace.refine_resonance()

        # Convergence: a run that hit the timestep cap has not settled, and the
        # resonance minimum can still move (review item N-02).
        log_text = ""
        for name in ("run.stdout.log", "run.stderr.log"):
            candidate = run_path / name
            if candidate.exists():
                log_text += candidate.read_text(encoding="utf-8", errors="replace")
        cap_hit = "Max. number of timesteps was reached" in log_text
        iterations = None
        for line in log_text.splitlines():
            if line.startswith("Time for") and "iterations" in line:
                try:
                    iterations = int(line.split()[2])
                except (IndexError, ValueError):
                    pass
        converged = bool(log_text) and not cap_hit
        convergence_note = (
            "solver log not found: convergence unknown"
            if not log_text
            else (
                "hit the max-timestep cap before the end criteria: NOT converged"
                if cap_hit
                else "end criteria reached before the timestep cap"
            )
        )

        # Far-field data is optional: it exists only when the NF2FF box was enabled.
        # Radiation efficiency from the solver is the quantity that lets the loss
        # model be validated at all (review item A-2).
        farfield_data = None
        farfield_summary = run_path / "nf2ff_summary.csv"
        if farfield_summary.exists():
            try:
                from ..postproc.farfield import read_summary

                farfield_data = [point.to_dict() for point in read_summary(farfield_summary)]
            except Exception as exc:
                farfield_data = {"error": f"{type(exc).__name__}: {exc}"}
        return {
            "solver": self.name,
            "frequencies_hz": trace.frequencies_hz,
            "s11_re": [s.real for s in trace.s11],
            "s11_im": [s.imag for s in trace.s11],
            "vswr_at_resonance": vswr_from_gamma(abs(trace.s11[trace.worst_match_index()])),
            "resonance_hz": trace.resonance_hz(),
            "resonance_refined_hz": refined_hz,
            "resonance_grid_step_hz": grid_step_hz,
            "resonance_curvature_db_per_hz2": dip_curvature,
            "worst_match_db": trace.worst_match_db(),
            "bands_below_minus10db": [
                {"f_start_hz": a, "f_stop_hz": b, "bandwidth_hz": c} for a, b, c in bands
            ],
            "fractional_bandwidth": trace.fractional_bandwidth(-10.0),
            "converged": converged,
            "convergence_note": convergence_note,
            "timesteps": iterations,
            "farfield": farfield_data,
            "source": str(csv_path),
            "verified": False,
        }
