"""openEMS / CSXCAD adapter.

PHASE 1 SCOPE - READ THIS FIRST
-------------------------------
This module **generates** a runnable openEMS model script from the neutral
project model.  It does not, and cannot, execute it here:

* no openEMS/CSXCAD runtime was installed in the environment where this module
  was written, so :meth:`OpenEMSSolver.available` returns ``False`` there;
* the generated script has therefore only been **statically reviewed** against
  the documented CSXCAD/openEMS Python API.  It is explicitly *not* a verified
  simulation.  Expect to correct API details on the first real run and record
  what changed.

Licensing: openEMS is GPL-3.0-or-later and CSXCAD is LGPL-3.0-or-later.  Both are
driven here as **external programs** via generated scripts and files, never as
imported libraries, so this MIT-licensed package stays a separate work.  See
``docs/licensing.md``.

Geometry conventions used by the generated script (metres, right-handed):

* z = 0 is the top of the substrate (the patch plane);
* the substrate occupies ``z in [-h_total, 0]``;
* the ground plane sits just below the substrate;
* patch width ``W`` along x, patch length ``L`` along y;
* the feed (lumped port) runs along z from the ground plane up to the patch;
  its (x, y) position depends on ``feed_mode``:
    - ``edge``  -> y = +L/2 (radiating edge)
    - ``inset`` -> y = +L/2 - inset_depth
    - ``probe`` -> (0, 0), i.e. the patch centre
"""

from __future__ import annotations

import json
import math
import os
import shutil
import sys
from importlib import util as importlib_util
from pathlib import Path
from string import Template
from typing import Any, Dict, Optional

from ..geometry.array import build_array_layout
from ..geometry.patch import ground_plane_size, synthesize_patch
from ..model.project import C0, Project
from .base import SolverAdapter, SolverRun, SolverStatus, SolverUnavailableError

GENERATOR_VERSION = "0.1.0"
EPS0 = 8.8541878128e-12  # vacuum permittivity [F/m]

_SCRIPT_TEMPLATE = Template(
    '''#!/usr/bin/env python
"""openEMS model generated by OpenAntenna Studio $VERSION.

Source project : $PROJECT_NAME
Generated by   : openantenna.solvers.openems.OpenEMSSolver.render_script()

*** THIS SCRIPT HAS NEVER BEEN EXECUTED ***
It was generated in an environment without an openEMS/CSXCAD runtime, so it has
only been reviewed statically against the documented Python API.  Expect to fix
details on the first real run, and write down what you changed.

Licensing: this script drives openEMS (GPL-3.0-or-later) and CSXCAD
(LGPL-3.0-or-later) as an external program.  It is not linked into, and is not
part of, OpenAntenna Studio (MIT).

Units: metres (SetDeltaUnit(1.0)), Hz.
Coordinate conventions: z = 0 is the top of the substrate; patch width W along
x, patch length L along y; the lumped port runs along z through the substrate.
"""

import json
import os
import sys

# --- Windows: the openEMS package ships its native DLLs (CSXCAD.dll,
# --- openEMS.dll, hdf5, vtk, ...) next to its executables.  Since Python 3.8
# --- extension modules no longer search PATH for dependent DLLs, so the
# --- directory must be registered explicitly before importing CSXCAD.
if os.name == "nt":
    _root = os.environ.get("OPENEMS_ROOT", "")
    if _root and os.path.isdir(_root):
        os.add_dll_directory(_root)
        os.environ["PATH"] = _root + os.pathsep + os.environ.get("PATH", "")
    else:
        print(
            "WARNING: OPENEMS_ROOT is not set to the openEMS install folder; "
            "importing CSXCAD/openEMS may fail on Windows.",
            file=sys.stderr,
        )

import numpy as np

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import C0

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- parameters
PROJECT_NAME = "$PROJECT_NAME"
F0 = $F0              # design / excitation centre frequency [Hz]
F_MIN = $F_MIN        # sweep start [Hz]
F_MAX = $F_MAX        # sweep stop [Hz]
N_FREQ = $N_FREQ      # sweep points

H_TOTAL = $H_TOTAL         # total substrate thickness [m]
EPS_SUB = $EPS_SUB         # substrate relative permittivity
KAPPA_SUB = $KAPPA_SUB     # substrate conductivity [S/m] (loss)
TAN_D_SUB = $TAN_D_SUB     # substrate loss tangent at F0 (reference value)
MU_SUB = $MU_SUB
LOSS_MODEL = "$LOSS_MODEL"  # "kappa" (equivalent conductivity) or "none"
EPS0 = 8.8541878128e-12

W_PATCH = $W_PATCH         # patch width along x [m]
L_PATCH = $L_PATCH         # patch length along y [m]
GROUND_X = $GROUND_X       # ground plane size along x [m]
GROUND_Y = $GROUND_Y       # ground plane size along y [m]
GROUND_MARGIN_LAMBDA = $GROUND_MARGIN_LAMBDA   # margin per side, in lambda0
CONDUCTOR_MODEL = "$CONDUCTOR_MODEL"   # metals are ideal PEC: conductor loss is NOT modelled

FEED_X = $FEED_X
FEED_Y = $FEED_Y
FEED_INSET = $FEED_INSET
FEED_Z0 = $FEED_Z0         # port reference impedance [ohm]

MESH_MAX_RES = C0 / F_MAX / $MESH_CELLS_PER_WAVELENGTH
MESH_SUBSTRATE_CELLS = $MESH_SUBSTRATE_CELLS
PORT_REFINE = $PORT_REFINE   # refine the mesh around the lumped port (review item A4)
MESH_SMOOTHING = $MESH_SMOOTHING
METAL_EDGE_SNAPPING = $METAL_EDGE_SNAPPING
PML_CELLS = $PML_CELLS
BOUNDARY_MODE = "$BOUNDARY_MODE"
AIRBOX_LAMBDA = $AIRBOX_LAMBDA      # air margin around the structure, per side
AIR_TOP_LAMBDA = $AIR_TOP_LAMBDA    # air margin above the patch
MAX_TS = $MAX_TS
END_CRITERIA = $END_CRITERIA

# ---------------------------------------------------------------- FDTD setup
# The excitation must cover the whole sweep; use F0 as centre and half of F0 as
# the Gaussian half-width (the convention used by the openEMS tutorials).
FDTD = openEMS(NrTS=MAX_TS, EndCriteria=END_CRITERIA)
FDTD.SetGaussExcite(F0, 0.5 * F0)
if BOUNDARY_MODE == "MUR":
    # MUR (first-order absorbing) is what the openEMS patch tutorial uses; PML is
    # the better general choice but needs enough cells.  Which one shifts the
    # resonance, and by how much, is an open question from review (N-01/N-04).
    FDTD.SetBoundaryCond(["MUR"] * 6)
else:
    FDTD.SetBoundaryCond(["PML_%d" % PML_CELLS] * 6)
print("BOUNDARY: %s" % ("MUR" if BOUNDARY_MODE == "MUR" else "PML_%d" % PML_CELLS))

CSX = ContinuousStructure()
FDTD.SetCSX(CSX)
mesh = CSX.GetGrid()
mesh.SetDeltaUnit(1.0)   # everything below is in metres

# ---------------------------------------------------------------- loss check
def implied_tan_delta(frequency_hz):
    """tan_delta that KAPPA_SUB actually represents at a given frequency.

    A constant conductivity gives tan_delta(f) = kappa / (2*pi*f*eps0*eps_r),
    so it equals the target value exactly at F0 and drifts as 1/f away from it.
    """
    if KAPPA_SUB <= 0:
        return 0.0
    return KAPPA_SUB / (2.0 * np.pi * frequency_hz * EPS0 * EPS_SUB)


print("LOSS MODEL: %s" % LOSS_MODEL)
if LOSS_MODEL == "kappa" and KAPPA_SUB > 0:
    print("  target tan_delta at F0 = %.6g" % TAN_D_SUB)
    print(
        "  implied tan_delta at %.4g / %.4g / %.4g Hz: %.6g / %.6g / %.6g"
        % (F_MIN, F0, F_MAX, implied_tan_delta(F_MIN), implied_tan_delta(F0), implied_tan_delta(F_MAX))
    )
    print("  NOTE: constant-sigma approximation; it is exact at F0 only.")
else:
    print("  lossless substrate (kappa = 0): no dielectric loss in this model.")

# ---------------------------------------------------------------- geometry
substrate = CSX.AddMaterial("substrate", epsilon=EPS_SUB, mue=MU_SUB, kappa=KAPPA_SUB)
substrate.AddBox(
    [-GROUND_X / 2.0, -GROUND_Y / 2.0, -H_TOTAL],
    [GROUND_X / 2.0, GROUND_Y / 2.0, 0.0],
    priority=1,
)

# Metals are modelled as infinitely thin sheets: a degenerate box whose start
# and stop coincide in z.  openEMS snaps such a sheet onto the mesh.  Forcing a
# physical metal thickness here would create ~35 um cells, which collapses the
# FDTD timestep (observed: dt = 6.5e-14 s at 35 um) and wastes hours.
ground = CSX.AddMetal("ground")
ground.AddBox(
    [-GROUND_X / 2.0, -GROUND_Y / 2.0, -H_TOTAL],
    [GROUND_X / 2.0, GROUND_Y / 2.0, -H_TOTAL],
    priority=2,
)

# Radiating elements, one thin sheet per array element.
ELEMENTS = $ELEMENTS_LITERAL
_patch_props = []
for index, (x0, y0) in enumerate(ELEMENTS, start=1):
    patch = CSX.AddMetal("patch_%d" % index)
    patch.AddBox(
        [x0 - W_PATCH / 2.0, y0 - L_PATCH / 2.0, 0.0],
        [x0 + W_PATCH / 2.0, y0 + L_PATCH / 2.0, 0.0],
        priority=3,
    )
    _patch_props.append(patch)

if METAL_EDGE_SNAPPING:
    # Force mesh lines exactly on the metal edges, as the openEMS patch tutorial
    # does with AddEdges2Grid.  Without it a degenerate (zero-thickness) sheet can
    # be snapped to the neighbouring cell, which changes the *effective* patch
    # size - a candidate for the 4.31 % offset observed against the tutorial.
    FDTD.AddEdges2Grid(dirs="xy", properties=ground, metal_edge_res=MESH_MAX_RES / 2.0)
    for _prop in _patch_props:
        FDTD.AddEdges2Grid(dirs="xy", properties=_prop, metal_edge_res=MESH_MAX_RES / 2.0)
    print("METAL EDGES: snapped to the grid (AddEdges2Grid, res %.3f mm)" % (MESH_MAX_RES / 2.0 * 1e3))

# Feed realisation.  CAREFUL - what this actually models: a *vertical lumped
# port* from the ground plane up through the substrate to the patch, i.e. a
# probe/coax feed.  FEED_Y is shifted by the inset depth, so feed_mode="inset"
# only moves the probe; it is NOT a coplanar inset line with a notch.  The
# closed-form inset formula used by the synthesis describes a coplanar inset
# feed, so this model cannot validate that formula (review item Y-19).
#
# ``edges2grid`` snaps the port box onto the mesh; without it openEMS reports
# "Unused primitive (type: Box) ... port_excite", the port never excites and every
# S11 value comes out NaN.
# NOTE: a real NxM array also needs a feed network and one port per element (or a
# proper corporate-feed model).  Phase 1 models ONE port only.
print("CONDUCTOR: %s (conductor loss not modelled)" % CONDUCTOR_MODEL)
print("FEED: vertical lumped port (probe); inset depth = %.3f mm" % (FEED_INSET * 1e3))
print(
    "GROUND: %.3f x %.3f mm (margin %.3f lambda0 per side; the ground plane is part "
    "of the radiating structure - review item N-01)"
    % (GROUND_X * 1e3, GROUND_Y * 1e3, GROUND_MARGIN_LAMBDA)
)
port = FDTD.AddLumpedPort(
    1,
    FEED_Z0,
    [FEED_X, FEED_Y, -H_TOTAL],
    [FEED_X, FEED_Y, 0.0],
    "z",
    1.0,
    priority=5,
    edges2grid="xy",
)

# ---------------------------------------------------------------- meshing
# The simulation domain must contain air above and around the structure,
# otherwise the absorbing boundary has nothing to absorb: openEMS then reports
# "Not enough lines in direction 2, resetting to PEC" and the run is a closed
# metal box rather than a radiating antenna.
lambda_min = C0 / F_MAX
DOM_X = GROUND_X / 2.0 + AIRBOX_LAMBDA * lambda_min
DOM_Y = GROUND_Y / 2.0 + AIRBOX_LAMBDA * lambda_min
DOM_Z_BOT = -(H_TOTAL + AIRBOX_LAMBDA * lambda_min)
DOM_Z_TOP = AIR_TOP_LAMBDA * lambda_min

CSX.AddMaterial("air").AddBox(
    [-DOM_X, -DOM_Y, DOM_Z_BOT], [DOM_X, DOM_Y, DOM_Z_TOP], priority=0
)

# Structure edges are added as explicit mesh lines so that the substrate,
# patch and feed land exactly on cell boundaries; the free-space regions then
# get a coarser staircase which SmoothMeshLines refines.
mesh.AddLine("x", np.linspace(-DOM_X, DOM_X, 25))
mesh.AddLine("y", np.linspace(-DOM_Y, DOM_Y, 25))
mesh.AddLine("x", [-W_PATCH / 2.0, W_PATCH / 2.0, FEED_X])
mesh.AddLine("y", [-L_PATCH / 2.0, L_PATCH / 2.0, FEED_Y])
for x0, y0 in ELEMENTS:
    mesh.AddLine("x", [x0 - W_PATCH / 2.0, x0 + W_PATCH / 2.0])
    mesh.AddLine("y", [y0 - L_PATCH / 2.0, y0 + L_PATCH / 2.0])
mesh.AddLine("z", np.linspace(-H_TOTAL, 0.0, MESH_SUBSTRATE_CELLS + 1))
mesh.AddLine("z", [DOM_Z_BOT, -H_TOTAL, 0.0, DOM_Z_TOP])
mesh.AddLine("z", np.linspace(0.0, DOM_Z_TOP, 9))
mesh.AddLine("z", np.linspace(DOM_Z_BOT, -H_TOTAL, 5))

if PORT_REFINE:
    # Refine the mesh around the feed.  The lumped port feeds a load across the
    # substrate; if the lateral cell there is the coarse free-space cell, the
    # excitation is badly discretised and the port contributes series inductance
    # to the model - a candidate for the residual construction bias
    # (Yotta review item A4).  The refinement uses the substrate cell size.
    _port_cell = H_TOTAL / MESH_SUBSTRATE_CELLS
    _port_half = 2.0 * _port_cell
    mesh.AddLine("x", np.linspace(FEED_X - _port_half, FEED_X + _port_half, 5))
    mesh.AddLine("y", np.linspace(FEED_Y - _port_half, FEED_Y + _port_half, 5))
    print(
        "PORT REFINE: %.4f mm cells over %.4f mm around the feed"
        % (_port_cell * 1e3, 2.0 * _port_half * 1e3)
    )

mesh.SmoothMeshLines("all", MESH_MAX_RES, MESH_SMOOTHING)

print(
    "DOMAIN: x=[%.1f, %.1f] y=[%.1f, %.1f] z=[%.1f, %.1f] mm"
    % (
        -DOM_X * 1e3, DOM_X * 1e3,
        -DOM_Y * 1e3, DOM_Y * 1e3,
        DOM_Z_BOT * 1e3, DOM_Z_TOP * 1e3,
    )
)


def main():
    sim_path = os.path.join(HERE, "openems_run")
    FDTD.Run(sim_path, verbose=3, cleanup=True)

    freqs = np.linspace(F_MIN, F_MAX, N_FREQ)
    port.CalcPort(sim_path, freqs, FEED_Z0)
    s11 = port.uf_ref / port.uf_inc

    out_path = os.path.join(HERE, "s11.csv")
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("freq_hz,s11_re,s11_im\\n")
        for frequency, value in zip(freqs, s11):
            handle.write("%.6e,%.9e,%.9e\\n" % (frequency, value.real, value.imag))

    with open(os.path.join(HERE, "run_summary.json"), "w", encoding="utf-8") as handle:
        json.dump(
            {
                "solver": "openEMS",
                "project": PROJECT_NAME,
                "f_min_hz": float(F_MIN),
                "f_max_hz": float(F_MAX),
                "n_freq": int(N_FREQ),
                "s11_csv": out_path,
                "note": "generated by OpenAntenna Studio; verify before trusting",
            },
            handle,
            indent=2,
        )
    print("wrote", out_path)


if __name__ == "__main__":
    main()
'''
)


class OpenEMSSolver(SolverAdapter):
    """Adapter that renders and (when possible) runs an openEMS model."""

    name = "openems"
    script_name = "sim.py"
    project_name = "project.json"
    results_name = "s11.csv"

    def __init__(
        self,
        mesh_cells_per_wavelength: int = 15,
        substrate_cells: int = 8,
        air_margin_lambda: float = 0.20,
        air_top_lambda: float = 0.30,
        loss_model: str = "kappa",
        ground_margin_lambda: float = 0.25,
        boundary: str = "PML",
        pml_cells: int = 8,
        mesh_smoothing_ratio: float = 1.4,
        metal_edge_snapping: bool = True,
        port_refine: bool = True,
        max_timesteps: int = 400000,
        end_criteria: float = 1e-4,
    ) -> None:
        """Create an adapter with explicit mesh-resolution controls.

        The defaults are a *fast* setting, not a converged one.  Mesh
        convergence must be established per design by re-running with finer
        values; nothing in this package has been calibrated yet.
        """
        if mesh_cells_per_wavelength < 4:
            raise ValueError("mesh_cells_per_wavelength must be >= 4")
        if substrate_cells < 2:
            raise ValueError("substrate_cells must be >= 2")
        if air_margin_lambda <= 0 or air_top_lambda <= 0:
            raise ValueError("air margins must be > 0")
        if loss_model not in ("kappa", "none"):
            raise ValueError("loss_model must be 'kappa' or 'none'")
        if ground_margin_lambda <= 0:
            raise ValueError("ground_margin_lambda must be > 0")
        if boundary not in ("PML", "MUR"):
            raise ValueError("boundary must be 'PML' or 'MUR'")
        if pml_cells < 2:
            raise ValueError("pml_cells must be >= 2")
        if mesh_smoothing_ratio <= 1.0:
            raise ValueError("mesh_smoothing_ratio must be > 1")
        if max_timesteps < 100:
            raise ValueError("max_timesteps must be >= 100")
        if end_criteria <= 0:
            raise ValueError("end_criteria must be > 0")
        self.boundary = boundary
        self.pml_cells = int(pml_cells)
        self.mesh_smoothing_ratio = float(mesh_smoothing_ratio)
        self.metal_edge_snapping = bool(metal_edge_snapping)
        self.port_refine = bool(port_refine)
        self.max_timesteps = int(max_timesteps)
        self.end_criteria = float(end_criteria)
        self.ground_margin_lambda = float(ground_margin_lambda)
        self.loss_model = loss_model
        self.last_kappa = 0.0
        self.last_reference_frequency_hz = None
        self.mesh_cells_per_wavelength = int(mesh_cells_per_wavelength)
        self.substrate_cells = int(substrate_cells)
        self.air_margin_lambda = float(air_margin_lambda)
        self.air_top_lambda = float(air_top_lambda)

    # ----------------------------------------------------------------- probe
    @staticmethod
    def resolve_root() -> Optional[str]:
        """Locate the openEMS installation folder (native DLLs + executables).

        Resolution order: ``OPENEMS_ROOT`` environment variable, then the
        folder containing an ``openEMS`` executable on PATH.
        """
        env = os.environ.get("OPENEMS_ROOT")
        if env and Path(env).is_dir():
            return str(Path(env))
        exe = shutil.which("openEMS") or shutil.which("openems")
        if exe:
            return str(Path(exe).parent)
        return None

    def available(self) -> SolverStatus:
        root = self.resolve_root()
        binary = None
        if root:
            for candidate in ("openEMS.exe", "openEMS"):
                path = Path(root) / candidate
                if path.exists():
                    binary = str(path)
                    break
        binary = binary or shutil.which("openEMS") or shutil.which("openems")
        have_csxcad = importlib_util.find_spec("CSXCAD") is not None
        have_openems_py = importlib_util.find_spec("openEMS") is not None

        missing = []
        if binary is None:
            missing.append("openEMS executable (not on PATH)")
        if not have_csxcad:
            missing.append("python module 'CSXCAD'")
        if not have_openems_py:
            missing.append("python module 'openEMS'")

        if missing:
            return SolverStatus(
                name=self.name,
                available=False,
                detail=(
                    "openEMS cannot be executed here; missing: " + ", ".join(missing)
                    + ". Model generation still works. Set OPENEMS_ROOT to the "
                    "folder that contains openEMS.exe / CSXCAD.dll."
                ),
                binary_path=binary,
            )
        return SolverStatus(
            name=self.name,
            available=True,
            detail=(
                "openEMS executable and CSXCAD/openEMS python modules found"
                + (f" (root: {root})" if root else "")
                + "."
            ),
            binary_path=binary,
        )

    # --------------------------------------------------------------- prepare
    def render_script(self, project: Project) -> str:
        """Render the openEMS python script for ``project`` (no I/O)."""
        layers = project.substrate.dielectric_layers() or project.substrate.layers
        if len(layers) > 1:
            raise ValueError(
                "the Phase 1 openEMS generator supports a single dielectric layer; "
                f"got {len(layers)}. Collapse the stackup to an effective medium first."
            )
        layer = layers[0]

        material_name = layer.material
        epsilon_r = 1.0
        tan_delta = 0.0
        mu_r = 1.0
        try:
            from ..materials.library import get_material

            material = get_material(material_name)
            epsilon_r = float(material.epsilon_r)
            tan_delta = float(material.tan_delta)
            mu_r = float(material.mu_r)
        except KeyError:
            raise ValueError(
                f"unknown substrate material {material_name!r}; define it in the "
                "material library before generating solver input"
            ) from None

        # Dielectric loss.  A constant conductivity reproduces the requested loss
        # tangent exactly at the reference frequency (the sweep centre) and drifts
        # as 1/f away from it; the generated script prints the implied tan_delta
        # at the sweep edges so that drift is visible rather than hidden.
        # loss_model="none" produces a lossless substrate.
        if self.loss_model == "none" or tan_delta <= 0.0:
            kappa_sub = 0.0
        else:
            kappa_sub = (
                2.0 * math.pi * project.sweep.center_hz * EPS0 * epsilon_r * tan_delta
            )
        self.last_kappa = kappa_sub
        self.last_reference_frequency_hz = project.sweep.center_hz

        design = synthesize_patch(
            frequency_hz=project.sweep.center_hz,
            epsilon_r=epsilon_r,
            height_m=layer.thickness_m,
            feed_mode=project.patch.feed_mode,
        )
        width = project.patch.width_m or design.width_m
        length = project.patch.length_m or design.length_m
        ground_x, ground_y = ground_plane_size(
            width,
            length,
            project.sweep.center_hz,
            margin_lambda=self.ground_margin_lambda,
        )

        layout = build_array_layout(project.array, project.sweep.center_hz, design)

        if project.patch.feed_mode == "inset":
            inset = project.patch.feed_inset_m or design.inset_depth_m
            feed_y = length / 2.0 - inset
            feed_x = 0.0
        elif project.patch.feed_mode == "edge":
            feed_x = 0.0
            feed_y = length / 2.0
        elif project.patch.feed_mode == "probe":
            feed_x = 0.0
            feed_y = 0.0
        else:  # corporate feed network is a Phase 2 feature
            feed_x = 0.0
            feed_y = length / 2.0

        conductor_model = "PEC"

        def fmt(value: float) -> str:
            return f"{value:.10g}"

        return _SCRIPT_TEMPLATE.substitute(
            VERSION=GENERATOR_VERSION,
            PROJECT_NAME=project.name,
            F0=fmt(project.sweep.center_hz),
            F_MIN=fmt(project.sweep.start_hz),
            F_MAX=fmt(project.sweep.stop_hz),
            N_FREQ=project.sweep.points,
            H_TOTAL=fmt(project.substrate.total_thickness_m),
            EPS_SUB=fmt(epsilon_r),
            KAPPA_SUB=fmt(kappa_sub),
            TAN_D_SUB=fmt(tan_delta),
            MU_SUB=fmt(mu_r),
            LOSS_MODEL=self.loss_model,
            W_PATCH=fmt(width),
            L_PATCH=fmt(length),
            GROUND_X=fmt(ground_x),
            GROUND_Y=fmt(ground_y),
            GROUND_MARGIN_LAMBDA=fmt(self.ground_margin_lambda),
            CONDUCTOR_MODEL=conductor_model,
            FEED_X=fmt(feed_x),
            FEED_Y=fmt(feed_y),
            FEED_INSET=fmt(project.patch.feed_inset_m or design.inset_depth_m),
            FEED_Z0=fmt(50.0),
            MESH_CELLS_PER_WAVELENGTH=self.mesh_cells_per_wavelength,
            MESH_SUBSTRATE_CELLS=self.substrate_cells,
            MESH_SMOOTHING=fmt(self.mesh_smoothing_ratio),
            METAL_EDGE_SNAPPING="True" if self.metal_edge_snapping else "False",
            PORT_REFINE="True" if self.port_refine else "False",
            PML_CELLS=self.pml_cells,
            BOUNDARY_MODE=self.boundary,
            AIRBOX_LAMBDA=fmt(self.air_margin_lambda),
            AIR_TOP_LAMBDA=fmt(self.air_top_lambda),
            MAX_TS=self.max_timesteps,
            END_CRITERIA=fmt(self.end_criteria),
            ELEMENTS_LITERAL=repr(
                [[float(x), float(y)] for x, y in layout.positions_m]
            ),
        )

    def prepare(self, project: Project, rundir: str | Path) -> Path:
        run_path = Path(rundir)
        run_path.mkdir(parents=True, exist_ok=True)
        (run_path / self.project_name).write_text(project.to_json() + "\n", encoding="utf-8")
        (run_path / self.script_name).write_text(self.render_script(project), encoding="utf-8")

        warnings = project.check()
        lambda_min = C0 / project.sweep.stop_hz
        meta = {
            "solver": self.name,
            "generator_version": GENERATOR_VERSION,
            "project": project.name,
            "verified": False,
            "conductor_model": "PEC (ideal; conductor loss is not modelled) - review item Y-03",
            "ground_margin_lambda": self.ground_margin_lambda,
            "boundary": self.boundary,
            "pml_cells": self.pml_cells,
            "mesh_smoothing_ratio": self.mesh_smoothing_ratio,
            "metal_edge_snapping": self.metal_edge_snapping,
            "max_timesteps": self.max_timesteps,
            "end_criteria": self.end_criteria,
            "mesh": {
                "cells_per_wavelength": self.mesh_cells_per_wavelength,
                "substrate_cells": self.substrate_cells,
                "port_refine": self.port_refine,
                "air_margin_lambda": self.air_margin_lambda,
                "air_top_lambda": self.air_top_lambda,
                "air_margin_m": self.air_margin_lambda * lambda_min,
                "free_space_to_pml_m": self.air_margin_lambda * lambda_min,
                "pml_cells": self.pml_cells,
                "pml_thickness_m": self.pml_cells * lambda_min / self.mesh_cells_per_wavelength,
                "converged": False,
                "note": (
                    "free_space_to_pml_m is the nominal gap between the ground-plane "
                    "edge and the absorbing boundary; it is recorded so this quantity "
                    "can be checked instead of guessed (review item Y-18)"
                ),
            },
            "dielectric_loss": {
                "model": self.loss_model,
                "kappa_s_per_m": self.last_kappa,
                "reference_frequency_hz": self.last_reference_frequency_hz,
                "note": (
                    "constant-conductivity equivalent; exact at the reference "
                    "frequency only"
                    if self.loss_model == "kappa"
                    else "lossless substrate"
                ),
            },
            "verification_note": (
                "generated only; never executed against a real openEMS runtime in the "
                "environment where this file was produced"
            ),
            "warnings": warnings,
            "files": [self.script_name, self.project_name],
        }
        (run_path / "run_manifest.json").write_text(
            json.dumps(meta, indent=2) + "\n", encoding="utf-8"
        )
        return run_path.resolve()

    # ------------------------------------------------------------------- run
    def run(self, rundir: str | Path, timeout_s: Optional[float] = None) -> SolverRun:
        run_path = Path(rundir)
        status = self.available()
        if not status.available:
            raise SolverUnavailableError(
                f"{status.detail} Run the generated script on a machine that has "
                f"openEMS/CSXCAD installed: python {run_path / self.script_name}"
            )
        script = run_path / self.script_name
        if not script.exists():
            raise FileNotFoundError(f"{script} not found; call prepare() first")

        env = dict(os.environ)
        root = self.resolve_root()
        if root:
            env["OPENEMS_ROOT"] = root
            env["PATH"] = root + os.pathsep + env.get("PATH", "")
        run = self._execute([sys.executable, str(script)], run_path, timeout_s, env=env)
        # Persist the solver log next to the results: convergence can only be
        # judged from it, and without it a run cannot be audited (review item N-02).
        (run_path / "run.stdout.log").write_text(run.log or "", encoding="utf-8")
        return run

    # --------------------------------------------------------------- results
    def parse_results(self, rundir: str | Path) -> Dict[str, Any]:
        run_path = Path(rundir)
        csv_path = run_path / self.results_name
        if not csv_path.exists():
            raise FileNotFoundError(
                f"{csv_path} not found; the solver has not produced results yet "
                "(expected columns: freq_hz,s11_re,s11_im)"
            )
        frequencies = []
        reals = []
        imags = []
        for index, line in enumerate(csv_path.read_text(encoding="utf-8").splitlines()):
            line = line.strip()
            if not line:
                continue
            if index == 0 and line.lower().startswith("freq"):
                continue
            parts = line.split(",")
            if len(parts) < 3:
                raise ValueError(f"unexpected row in {csv_path.name}: {line!r}")
            frequencies.append(float(parts[0]))
            reals.append(float(parts[1]))
            imags.append(float(parts[2]))
        if not frequencies:
            raise ValueError(f"no data rows in {csv_path}")

        from ..postproc.sparams import S11Trace, vswr_from_gamma

        trace = S11Trace(frequencies, [complex(r, i) for r, i in zip(reals, imags)])
        bands = trace.bandwidth_below(-10.0)

        # Convergence: a run that hit the timestep cap has not settled, and the
        # resonance minimum can still move (review item N-02).
        log_text = ""
        for name in ("run.stdout.log", "run.stderr.log"):
            candidate = run_path / name
            if candidate.exists():
                log_text += candidate.read_text(encoding="utf-8", errors="replace")
        cap_hit = "Max. number of timesteps was reached" in log_text
        iterations = None
        for line in log_text.splitlines():
            if line.startswith("Time for") and "iterations" in line:
                try:
                    iterations = int(line.split()[2])
                except (IndexError, ValueError):
                    pass
        converged = bool(log_text) and not cap_hit
        convergence_note = (
            "solver log not found: convergence unknown"
            if not log_text
            else (
                "hit the max-timestep cap before the end criteria: NOT converged"
                if cap_hit
                else "end criteria reached before the timestep cap"
            )
        )
        return {
            "solver": self.name,
            "frequencies_hz": trace.frequencies_hz,
            "s11_re": [s.real for s in trace.s11],
            "s11_im": [s.imag for s in trace.s11],
            "vswr_at_resonance": vswr_from_gamma(abs(trace.s11[trace.worst_match_index()])),
            "resonance_hz": trace.resonance_hz(),
            "worst_match_db": trace.worst_match_db(),
            "bands_below_minus10db": [
                {"f_start_hz": a, "f_stop_hz": b, "bandwidth_hz": c} for a, b, c in bands
            ],
            "fractional_bandwidth": trace.fractional_bandwidth(-10.0),
            "converged": converged,
            "convergence_note": convergence_note,
            "timesteps": iterations,
            "source": str(csv_path),
            "verified": False,
        }
